name: CD - Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs only when code is pushed to main

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Deploy to GitHub Pages
        run: yarn deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
